# Generated by Django 4.2.20 on 2025-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Contraloría UMSNH', max_length=200)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('quienes_somos', models.TextField()),
                ('organigrama', models.ImageField(blank=True, null=True, upload_to='organigramas/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
