# Generated by Django 4.2.20 on 2025-05-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginainicio',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner principal (recomendado 1920x600 px)', null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='paginainicio',
            name='texto_banner',
            field=models.CharField(blank=True, help_text='Texto descriptivo para el banner', max_length=200),
        ),
    ]
