# Generated by Django 4.2.20 on 2025-05-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('tipo', models.CharField(choices=[('DOC', 'Documento'), ('EXT', 'Aplicación Externa'), ('PAG', 'Página Web')], default='DOC', max_length=3)),
                ('imagen', models.ImageField(blank=True, help_text='Logo o imagen representativa (recomendado 300x300px)', null=True, upload_to='enlaces/')),
                ('icono', models.CharField(default='bi bi-link-45deg', help_text='Clase de Bootstrap Icons (opcional si no hay imagen)', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Enlaces',
                'ordering': ['orden'],
            },
        ),
    ]
