# Generated by Django 4.2.20 on 2025-05-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulares.anio')),
            ],
            options={
                'ordering': ['anio', 'mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='circulares/%Y/%m/')),
                ('fecha', models.DateField()),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulares.mes')),
            ],
            options={
                'ordering': ['-fecha', 'numero'],
            },
        ),
    ]
